*&---------------------------------------------------------------------*
*& Report ZDOMAIN_VALUE_01_KJH
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDOMAIN_VALUE_01_KJH.

TYPES: BEGIN OF TY_S_LIST,
         MANDT       TYPE MANDT,
         MTEXT       TYPE MTEXT_D,
         ORT01       TYPE ORT01,
         MWAER       TYPE MWAER,
         ADRNR       TYPE CHAR10,
         CCCATEGORY  TYPE CCCATEGORY,
         CCTEXT1(30),
         CCCORACTIV  TYPE CCCORACTIV,
         CCTEXT2(50),
         CCNOCLIIND  TYPE CCNOCLIIND,
         CCCOPYLOCK  TYPE CCCOPYLOCK,
         CCNOCASCAD  TYPE CCNOCASCAD,
         CCSOFTLOCK  TYPE CCSOFTLOCK,
         CCORIGCONT  TYPE CCORIGCONT,
         CCIMAILDIS  TYPE CCIMAILDIS,
         CCTEMPLOCK  TYPE CCTEMPLOCK,
         CHANGEUSER  TYPE AS4USER,
         CHANGEDATE  TYPE AS4DATE,
         LOGSYS      TYPE  LOGSYS,
       END OF TY_S_LIST.

DATA:
  GT_LIST    TYPE TABLE OF TY_S_LIST,
  GS_LIST    TYPE TY_S_LIST,

  LT1_DDTEXT TYPE TABLE OF DD07V,
  LS1_DDTEXT TYPE DD07V,

  LT2_DDTEXT TYPE TABLE OF DD07V,
  LS2_DDTEXT TYPE DD07V.


SELECT *
  FROM T000
  INTO CORRESPONDING FIELDS OF TABLE GT_LIST.

CALL FUNCTION 'DD_DOMVALUES_GET'
  EXPORTING
    DOMNAME        = 'CCCATEGORY'
    TEXT           = 'X'
  TABLES
    DD07V_TAB      = LT1_DDTEXT
  EXCEPTIONS
    WRONG_TEXTFLAG = 1
    OTHERS         = 2.

CALL FUNCTION 'DD_DOMVALUES_GET'
  EXPORTING
    DOMNAME        = 'CCCORACTIV'
    TEXT           = 'X'
  TABLES
    DD07V_TAB      = LT2_DDTEXT
  EXCEPTIONS
    WRONG_TEXTFLAG = 1
    OTHERS         = 2.



LOOP AT GT_LIST INTO GS_LIST.

READ TABLE LT1_DDTEXT WITH KEY DOMVALUE_L = GS_LIST-CCCATEGORY
INTO LS1_DDTEXT.

READ TABLE LT2_DDTEXT WITH KEY DOMVALUE_L = GS_LIST-CCCORACTIV
INTO LS2_DDTEXT.

GS_LIST-CCTEXT1 = LS1_DDTEXT-DDTEXT.
GS_LIST-CCTEXT2 = LS2_DDTEXT-DDTEXT.

MODIFY: GT_LIST FROM GS_LIST TRANSPORTING CCTEXT1 CCTEXT2 .


ENDLOOP.





*-------------------------------------*
DATA:
  GR_SALV TYPE REF TO CL_SALV_TABLE.

DATA:
  LO_COLUMNS TYPE REF TO CL_SALV_COLUMNS_TABLE.

CL_SALV_TABLE=>FACTORY(
  IMPORTING
    R_SALV_TABLE = GR_SALV
  CHANGING
    T_TABLE = GT_LIST[]
).

LO_COLUMNS = GR_SALV->GET_COLUMNS( ).
LO_COLUMNS->SET_OPTIMIZE( ).

GR_SALV->DISPLAY( ).
*-------------------------------------*